In [77]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
from src.feature_loader import load_features
from src.cross_validation import CrossValidator
import src.util as util

Check class distribution of samples in data splits

In [78]:
LABEL_PATH = "data/participants.tsv"
AD_FTD_CN = {"A": 0, "F": 1, "C": 2}
AD_CN = {"A": 1, "C": 0}
FTD_CN = {"F": 1, "C": 0}
AD_FTD = {"A": 1, "F": 0}
band = "alpha"

In [79]:
# Load data for AD vs CN classification
print("Loading features and labels...")
features_AD, labels_AD, subjects_AD = load_features(
    label_map=AD_CN, band=band
)
print("Data loaded.")
print("Classification task:", AD_CN)

Loading features and labels...
Min windows per subject: 303
Max windows per subject: 1278
Data loaded.
Classification task: {'A': 1, 'C': 0}

In [94]:
# Check class distribution overall
overall_AD = pd.DataFrame({"label": labels_AD, "subject": subjects_AD})
print("Overall class distribution (AD vs CN):")
print(overall_AD["label"].value_counts())
print()
print("Overall class distribution (AD vs CN) ratios:")
print(overall_AD["label"].value_counts(normalize=True))

Overall class distribution (AD vs CN):
label
1    29009
0    24011
Name: count, dtype: int64

Overall class distribution (AD vs CN) ratios:
label
1    0.547133
0    0.452867
Name: proportion, dtype: float64

In [95]:
# Check class distribution in data splits

results_AD = []

# Set up outer cross-validation (LOSO)
outer_cv = CrossValidator(
    features=features_AD, labels=labels_AD, subjects=subjects_AD, 
    cv_strategy="loso", n_splits=None, test_size=None, shuffle=False, 
    random_state=123)

for fold, train_val_idx, test_idx in outer_cv.cv_loop():

    # Outer train/val class distribution
    outer_counts = pd.Series(labels_AD[train_val_idx]).value_counts()
    outer_ratios = pd.Series(labels_AD[train_val_idx]).value_counts(normalize=True)

    # Inner single split for train/val
    inner_split = CrossValidator(
        features=features_AD[train_val_idx],
        labels=labels_AD[train_val_idx],
        subjects=subjects_AD[train_val_idx],
        cv_strategy=None,
        n_splits=None,
        test_size=0.2,
        shuffle=True,
        random_state=123
    )
    _, train_idx, val_idx = next(inner_split.cv_loop())

    # Map back to original indices
    train_idx = train_val_idx[train_idx]
    val_idx = train_val_idx[val_idx]

    # Inner train class distribution
    inner_train_counts = pd.Series(labels_AD[train_idx]).value_counts()
    inner_train_ratios = pd.Series(labels_AD[train_idx]).value_counts(normalize=True)

    results_AD.append({
        "fold": fold,
        "test_subject": subjects_AD[test_idx][0],
        "outer_train_val_ratio_A": outer_ratios[1],
        "outer_train_val_ratio_C": outer_ratios[0],
        "inner_train_ratio_A": inner_train_ratios[1],
        "inner_train_ratio_C": inner_train_ratios[0]
    })

CV Strategy: Leave One Subject Out (LOSO)
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.

In [96]:
# Create DataFrame of results and calculate imbalance ratios
df_AD = pd.DataFrame(results_AD)

df_AD["outer_imbalance"] = (df_AD["outer_train_val_ratio_A"] - 0.5).abs()
df_AD["inner_imbalance"] = (df_AD["inner_train_ratio_A"] - 0.5).abs()

outer_cv_results = df_AD[["fold", "test_subject", "outer_train_val_ratio_A", "outer_train_val_ratio_C", "outer_imbalance"]]
inner_cv_results = df_AD[["fold", "test_subject", "inner_train_ratio_A", "inner_train_ratio_C", "inner_imbalance"]]

In [97]:
# Display outer CV results
print("Outer CV train/val class ratios (AD vs CN):")
outer_cv_results.sort_values(by="outer_imbalance", ascending=False)

Outer CV train/val class ratios (AD vs CN):

,fold,test_subject,outer_train_val_ratio_A,outer_train_val_ratio_C,outer_imbalance
47,47,sub-048,0.557501,0.442499,0.057501
39,39,sub-040,0.557244,0.442756,0.057244
41,41,sub-042,0.557222,0.442778,0.057222
61,61,sub-062,0.556528,0.443472,0.056528
37,37,sub-038,0.556453,0.443547,0.056453
...,...,...,...,...,...
13,13,sub-014,0.539039,0.460961,0.039039
33,33,sub-034,0.538729,0.461271,0.038729
15,15,sub-016,0.538702,0.461298,0.038702
30,30,sub-031,0.537120,0.462880,0.037120
9,9,sub-010,0.535948,0.464052,0.035948

In [87]:
# Display inner splits results
print("Inner split train class ratios (AD vs CN):")
inner_cv_results.sort_values(by="inner_imbalance", ascending=False)

Inner split train class ratios (AD vs CN):

,fold,test_subject,inner_train_ratio_A,inner_train_ratio_C,inner_imbalance
57,57,sub-058,0.581946,0.418054,0.081946
61,61,sub-062,0.580996,0.419004,0.080996
20,20,sub-021,0.580865,0.419135,0.080865
33,33,sub-034,0.580013,0.419987,0.080013
25,25,sub-026,0.578926,0.421074,0.078926
...,...,...,...,...,...
2,2,sub-003,0.529077,0.470923,0.029077
8,8,sub-009,0.528224,0.471776,0.028224
5,5,sub-006,0.527732,0.472268,0.027732
4,4,sub-005,0.526174,0.473826,0.026174
0,0,sub-001,0.507019,0.492981,0.007019

In [88]:
# Load data for FTD vs CN classification
print("Loading features and labels...")
features_FTD, labels_FTD, subjects_FTD = load_features(
    label_map=FTD_CN, band=band
)
print("Data loaded.")
print("Classification task:", FTD_CN)

Loading features and labels...
Min windows per subject: 476
Max windows per subject: 1011
Data loaded.
Classification task: {'F': 1, 'C': 0}

In [89]:
# Check classification label distribution overall
overall_FTD = pd.DataFrame({"label": labels_FTD, "subject": subjects_FTD})
print("Overall class distribution (FTD vs CN):")
print(overall_FTD["label"].value_counts())
print()
print("Overall class distribution (FTD vs CN) ratios:")
print(overall_FTD["label"].value_counts(normalize=True))

Overall class distribution (FTD vs CN):
label
0    24011
1    16510
Name: count, dtype: int64

Overall class distribution (FTD vs CN) ratios:
label
0    0.592557
1    0.407443
Name: proportion, dtype: float64

In [90]:
# Check class distribution in data splits

results_FTD = []

# Set up outer cross-validation (LOSO)
outer_cv = CrossValidator(
    features=features_FTD, labels=labels_FTD, subjects=subjects_FTD, 
    cv_strategy="loso", n_splits=None, test_size=None, shuffle=False, 
    random_state=123)

for fold, train_val_idx, test_idx in outer_cv.cv_loop():

    # Outer train/val class distribution
    outer_counts = pd.Series(labels_FTD[train_val_idx]).value_counts()
    outer_ratios = pd.Series(labels_FTD[train_val_idx]).value_counts(normalize=True)

    # Inner single split for train/val
    inner_split = CrossValidator(
        features=features_FTD[train_val_idx],
        labels=labels_FTD[train_val_idx],
        subjects=subjects_FTD[train_val_idx],
        cv_strategy=None,
        n_splits=None,
        test_size=0.2,
        shuffle=True,
        random_state=123
    )
    _, train_idx, val_idx = next(inner_split.cv_loop())

    # Map back to original indices
    train_idx = train_val_idx[train_idx]
    val_idx = train_val_idx[val_idx]

    # Inner train class distribution
    inner_train_counts = pd.Series(labels_FTD[train_idx]).value_counts()
    inner_train_ratios = pd.Series(labels_FTD[train_idx]).value_counts(normalize=True)

    results_FTD.append({
        "fold": fold,
    "test_subject": subjects_FTD[test_idx][0],
        "outer_train_val_ratio_F": outer_ratios[1],
        "outer_train_val_ratio_C": outer_ratios[0],
        "inner_train_ratio_F": inner_train_ratios[1],
        "inner_train_ratio_C": inner_train_ratios[0]
    })

CV Strategy: Leave One Subject Out (LOSO)
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.
Using single train-test split.

In [91]:
# Create DataFrame of results and calculate imbalance ratios
df_FTD = pd.DataFrame(results_FTD)

df_FTD["outer_imbalance"] = (df_FTD["outer_train_val_ratio_F"] - 0.5).abs()
df_FTD["inner_imbalance"] = (df_FTD["inner_train_ratio_F"] - 0.5).abs()

outer_cv_results = df_FTD[["fold", "test_subject", "outer_train_val_ratio_F", "outer_train_val_ratio_C", "outer_imbalance"]]
inner_cv_results = df_FTD[["fold", "test_subject", "inner_train_ratio_F", "inner_train_ratio_C", "inner_imbalance"]]

In [92]:
# Display outer CV results
print("Outer CV train/val class ratios (FTD vs CN):")
outer_cv_results.sort_values(by="outer_imbalance", ascending=False)

Outer CV train/val class ratios (FTD vs CN):

,fold,test_subject,outer_train_val_ratio_F,outer_train_val_ratio_C,outer_imbalance
37,37,sub-074,0.392280,0.607720,0.107720
43,43,sub-080,0.393799,0.606201,0.106201
46,46,sub-083,0.393830,0.606170,0.106170
41,41,sub-078,0.394487,0.605513,0.105513
36,36,sub-073,0.394732,0.605268,0.105268
44,44,sub-081,0.395189,0.604811,0.104811
39,39,sub-076,0.395280,0.604720,0.104720
42,42,sub-079,0.395311,0.604689,0.104689
51,51,sub-088,0.395798,0.604202,0.104202
45,45,sub-082,0.395904,0.604096,0.104096
38,38,sub-075,0.396345,0.603655,0.103655
40,40,sub-077,0.397087,0.602913,0.102913
35,35,sub-072,0.397722,0.602278,0.102278
47,47,sub-084,0.397798,0.602202,0.102202
30,30,sub-067,0.397934,0.602066,0.102066
32,32,sub-069,0.398040,0.601960,0.101960
34,34,sub-071,0.398311,0.601689,0.101689
50,50,sub-087,0.398552,0.601448,0.101448
49,49,sub-086,0.398914,0.601086,0.101086
31,31,sub-068,0.398989,0.601011,0.101011
48,48,sub-085,0.399184,0.600816,0.100816
29,29,sub-066,0.399350,0.600650,0.100650
33,33,sub-070,0.400400,0.599600,0.099600
23,23,sub-060,0.415074,0.584926,0.084926
9,9,sub-046,0.415127,0.584873,0.084873
14,14,sub-051,0.415127,0.584873,0.084873
21,21,sub-058,0.415158,0.584842,0.084842
15,15,sub-052,0.415200,0.584800,0.084800
0,0,sub-037,0.415377,0.584623,0.084623
16,16,sub-053,0.415409,0.584591,0.084591
12,12,sub-049,0.415409,0.584591,0.084591
22,22,sub-059,0.415482,0.584518,0.084518
19,19,sub-056,0.415524,0.584476,0.084476
20,20,sub-057,0.415576,0.584424,0.084424
24,24,sub-061,0.415649,0.584351,0.084351
26,26,sub-063,0.415660,0.584340,0.084340
10,10,sub-047,0.415691,0.584309,0.084309
18,18,sub-055,0.415764,0.584236,0.084236
13,13,sub-050,0.415796,0.584204,0.084204
6,6,sub-043,0.415921,0.584079,0.084079
17,17,sub-054,0.416005,0.583995,0.083995
27,27,sub-064,0.416121,0.583879,0.083879
2,2,sub-039,0.416142,0.583858,0.083858
8,8,sub-045,0.416152,0.583848,0.083848
7,7,sub-044,0.416467,0.583533,0.083533
28,28,sub-065,0.416498,0.583502,0.083502
4,4,sub-041,0.416520,0.583480,0.083480
1,1,sub-038,0.416572,0.583428,0.083428
25,25,sub-062,0.416646,0.583354,0.083354
5,5,sub-042,0.417330,0.582670,0.082670
3,3,sub-040,0.417351,0.582649,0.082649
11,11,sub-048,0.417605,0.582395,0.082395

In [93]:
# Display inner splits results
print("Inner split train class ratios (FTD vs CN):")
inner_cv_results.sort_values(by="inner_imbalance", ascending=False)

Inner split train class ratios (FTD vs CN):

,fold,test_subject,inner_train_ratio_F,inner_train_ratio_C,inner_imbalance
51,51,sub-088,0.392837,0.607163,0.107163
43,43,sub-080,0.396738,0.603262,0.103262
27,27,sub-064,0.401501,0.598499,0.098499
38,38,sub-075,0.411230,0.588770,0.088770
24,24,sub-061,0.411382,0.588618,0.088618
19,19,sub-056,0.411420,0.588580,0.088580
46,46,sub-083,0.411431,0.588569,0.088569
20,20,sub-057,0.411482,0.588518,0.088518
22,22,sub-059,0.411870,0.588130,0.088130
40,40,sub-077,0.412127,0.587873,0.087873
41,41,sub-078,0.412218,0.587782,0.087782
44,44,sub-081,0.413058,0.586942,0.086942
42,42,sub-079,0.413204,0.586796,0.086796
12,12,sub-049,0.413683,0.586317,0.086317
47,47,sub-084,0.413787,0.586213,0.086213
39,39,sub-076,0.413894,0.586106,0.086106
45,45,sub-082,0.413914,0.586086,0.086086
28,28,sub-065,0.414602,0.585398,0.085398
25,25,sub-062,0.415069,0.584931,0.084931
1,1,sub-038,0.415174,0.584826,0.084826
16,16,sub-053,0.416418,0.583582,0.083582
0,0,sub-037,0.416996,0.583004,0.083004
18,18,sub-055,0.418270,0.581730,0.081730
17,17,sub-054,0.418560,0.581440,0.081440
7,7,sub-044,0.419228,0.580772,0.080772
15,15,sub-052,0.420131,0.579869,0.079869
21,21,sub-058,0.420620,0.579380,0.079380
5,5,sub-042,0.422326,0.577674,0.077674
3,3,sub-040,0.423939,0.576061,0.076061
35,35,sub-072,0.428405,0.571595,0.071595
36,36,sub-073,0.431599,0.568401,0.068401
8,8,sub-045,0.431666,0.568334,0.068334
2,2,sub-039,0.433183,0.566817,0.066817
50,50,sub-087,0.436497,0.563503,0.063503
10,10,sub-047,0.436866,0.563134,0.063134
49,49,sub-086,0.436915,0.563085,0.063085
13,13,sub-050,0.436999,0.563001,0.063001
33,33,sub-070,0.437155,0.562845,0.062845
6,6,sub-043,0.437158,0.562842,0.062842
26,26,sub-063,0.438993,0.561007,0.061007
48,48,sub-085,0.439282,0.560718,0.060718
11,11,sub-048,0.439754,0.560246,0.060246
9,9,sub-046,0.441237,0.558763,0.058763
4,4,sub-041,0.441862,0.558138,0.058138
14,14,sub-051,0.444173,0.555827,0.055827
23,23,sub-060,0.445756,0.554244,0.054244
37,37,sub-074,0.448255,0.551745,0.051745
29,29,sub-066,0.453833,0.546167,0.046167
31,31,sub-068,0.454463,0.545537,0.045537
32,32,sub-069,0.454463,0.545537,0.045537
34,34,sub-071,0.454771,0.545229,0.045229
30,30,sub-067,0.456307,0.543693,0.043693